modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="seregamod"
version="228"
displayName="Serega Mod"
logoFile="examplemod.png"
credits="For Serega from Rustam"
authors="Love, Cheese and small house plants"
description='''
This mod soderzit pelmeni, olega i shlep
'''

[[dependencies.seregamod]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.seregamod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
